### PR TITLE
Add Transportation mode, promoCode Discount feature, Feedback, Show feedBack, Calender..

### PR DESCRIPTION
**Pull request by Meetpidev**
FeedBack is also stored in file..

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR..

**Comment by Meetpidev** [comment]
@soni-shashan Implemented Separate transport mode and Feedback.. Requested to review it

**Comment by Meetpidev** [comment]
@soni-shashan  apply promocode = meet

**Comment by Meetpidev** [comment]
### Here The Output Of All The Features..

### (1) Transportation Mode: ( At Starting ) 
image

### (2) Promocode Discount and Feed Back 
image

### (3) Calender.. 
Screenshot 2024-10-25 142124

**Comment by Meetpidev** [comment]
@soni-shashan Request to Review

**Comment by soni-shashan** [comment]
### @Meetpidev  You resolved multiple issues in one pull request totaling 14 points. If I assign a level 3 to this PR, you'll receive 8 points, but no more, according to Club Gamma's backend algorithm, which counts only the highest priority label points.

**Comment by Meetpidev** [comment]
@soni-shashan 
### So Request To assign me all these task.. i'll send PR one by one after one PR Accepted.. so that it has no conflicts

**Comment by soni-shashan** [comment]
### now close this pr you create separate prs for all issues done by you, and make sure there is no conflicts as recently I merge one pr

**Pull request closed without merging**
