### PR TITLE
Changed in option (3) and (4)

### LINKED ISSUE #55: Problem is option (3) and option (4)
### One more thing is that there should be separate option (9) for Exit system.. for better user experience...

### PR DESCRIPTION
**Pull request by Meetpidev**
### FIX OPTION 3,4 AND ADD EXIT AT 9TH PLACE..

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan REQUESTED TO REVIEW PR...

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR

**Comment by soni-shashan** [comment]
### @Meetpidev what is difference between option `4 & 9`

**Comment by soni-shashan** [comment]
### i think no need of option 9

**Comment by Meetpidev** [comment]
@soni-shashan 
### what if someone wants to see only Booking Tickets (Oprion 2) and after see it how can they exit from the system ? By select Option (9) they can exit...

### Think  about all the cases..

**Comment by soni-shashan** [comment]
Simply press exit without save

**Comment by Meetpidev** [comment]
> Simply press exit without save

### But we dont do any progress.. we just see Booking tickets.. (4)th option is for the progress.. like we pause at to enter destination... 4th option is not for exectly Exit

**Pull request merged**
