### PR TITLE
Added categories (e.g., standard, VIP) with different pricing structu…

### PR DESCRIPTION
**Pull request by Meetpidev**
…res in your ticket booking system

Added categories (e.g., standard, VIP) with different pricing structures in your ticket booking system

image
image

### CODE REVIEW

**Comment by Meetpidev** [comment]
@clubgama please review it

**Comment by Meetpidev** [comment]
@soni-shashan Please Review it..

**Comment by soni-shashan** [comment]
### @Meetpidev mention the issue in comment always something like `closes #issue-number` or `fixes #issue-number`, which will automatically close the issue ex: `fixes #40 : Added categories`

**Comment by soni-shashan** [comment]
### Fix Display Bookings In Your variant not work proper 
Screenshot 2024-10-22 122632

**Comment by Meetpidev** [comment]
image
@soni-shashan Fixed issue... please review it..

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR and let me know if any updates.. thank you..

**Comment by soni-shashan** [comment]
closes #6

**Comment by soni-shashan** [comment]
### @Meetpidev your code having unnecessary comments please fix it and create pr

**Pull request merged**
