### PR TITLE
added search booking

### PR DESCRIPTION
**Pull request by ayaan9618**
hi i added search booking
and can't find contribution list

Plz add hacktober label

### CODE REVIEW

**Comment by soni-shashan** [comment]
#### @ayaan9618 mention the issue in comment always something like `closes #issue-number` or `fixes #issue-number`, which will automatically close the issue ex: `fixes #40 : added search booking`

**Comment by soni-shashan** [comment]
### If there are multiple passengers with the same name and we try to search by name, it only shows the last booking with that name. Please fix this issue.

**Comment by soni-shashan** [comment]
#### @ayaan9618 There is no contribution list, so don't worry about it. It will be managed automatically by club gamma backed server.

**Comment by ayaan9618** [comment]
fixes #2 : added and updated search booking

and also plz add hackertober label to this

**Pull request merged**
