### PR TITLE
Added TransportMode and Different Price for Bus and Train

### LINKED ISSUE #62: Separate Booking for Bus and train travellers..
Initially ..User can choose whether they want to travel by Bus or Train..

### PR DESCRIPTION
**Pull request by Meetpidev**
### Added TransportMode and Different Price for Bus and Train

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Review Pr

**Comment by soni-shashan** [comment]
### proper menu not show previous gone like calander,etc.. and when ask for TransportMode?

**Comment by Meetpidev** [comment]
@soni-shashan Solved.. 

### There is the problem in current code regarding the menu... I fixed it in PR of FeedBack

**Comment by soni-shashan** [comment]
### fix display manu in #71 and update your code time by time

**Pull request merged**
