### PR TITLE
Payment by different Currency

### PR DESCRIPTION
**Pull request by Meetpidev**

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Requested to Review PR...

**Comment by soni-shashan** [comment]
PS C:\Users\shash\OneDrive\Documents\GitHub\Ticket-Booking> cd "c:\Users\shash\OneDrive\Documents\GitHub\Ticket-Booking\" ; if ($?) { gcc booking.c -o booking } ; if ($?) { .\booking }
booking.c: In function 'addBooking':
booking.c:772:37: warning: implicit declaration of function 'convertPrice' [-Wimplicit-function-declaration]
  772 |     float priceInSelectedCurrency = convertPrice(partial.booking.price, selectedCurrency);
      |                                     ^~~~~~~~~~~~
booking.c:807:18: warning: implicit declaration of function 'update_reedem_Points' [-Wimplicit-function-declaration]       
  807 |                  update_reedem_Points(partial.booking.name, partial.booking.price);
      |                  ^~~~~~~~~~~~~~~~~~~~
booking.c:808:38: warning: implicit declaration of function 'getPoints' [-Wimplicit-function-declaration]
  808 |                  int currentPoints = getPoints(partial.booking.name);
      |                                      ^~~~~~~~~
booking.c:822:44: warning: implicit declaration of function 'RedeemPoints' [-Wimplicit-function-declaration]
  822 |                       int redeemedPoints = RedeemPoints(partial.booking.name, pointsToRedeem);
      |                                            ^~~~~~~~~~~~
booking.c: At top level:
booking.c:921:6: warning: conflicting types for 'update_reedem_Points'
  921 | void update_reedem_Points(const char* userName, int bookingPrice) {
      |      ^~~~~~~~~~~~~~~~~~~~
booking.c:807:18: note: previous implicit declaration of 'update_reedem_Points' was here
  807 |                  update_reedem_Points(partial.booking.name, partial.booking.price);
      |                  ^~~~~~~~~~~~~~~~~~~~
booking.c: In function 'update_reedem_Points':
booking.c:937:29: warning: overflow in conversion from 'long long unsigned int' to 'long int' changes value from '18446744073709551560' to '-56' [-Woverflow]
  937 |                 fseek(file, -sizeof(struct User), SEEK_CUR);
      |                             ^~~~~~~~~~~~~~~~~~~~
booking.c: In function 'RedeemPoints':
booking.c:971:29: warning: overflow in conversion from 'long long unsigned int' to 'long int' changes value from '18446744073709551560' to '-56' [-Woverflow]
  971 |                 fseek(file, -sizeof(struct User), SEEK_CUR);
      |                             ^~~~~~~~~~~~~~~~~~~~
C:/SHASHAN-GCC/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\shash\AppData\Local\Temp\ccihdgiE.o:booking.c:(.text+0x1c9d): undefined reference to `convertPrice'
C:/SHASHAN-GCC/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\shash\AppData\Local\Temp\ccihdgiE.o:booking.c:(.text+0x27c3): undefined reference to `convertPrice'
C:/SHASHAN-GCC/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\shash\AppData\Local\Temp\ccihdgiE.o:booking.c:(.text+0x2883): undefined reference to `convertPrice'
collect2.exe: error: ld returned 1 exit status
PS C:\Users\shash\OneDrive\Documents\GitHub\Ticket-Booking>

**Comment by Meetpidev** [comment]
@soni-shashan Solved... Please Review Again...

**Comment by Meetpidev** [comment]
@soni-shashan Requested To Review Again...

**Comment by soni-shashan** [comment]
image
please remove this warnings 
image
see price section

**Pull request closed without merging**
