### PR TITLE
Modification or Cancellation bokking Features

### LINKED ISSUE #28: Booking Modification Feature
### Add functionality to allow users to modify or cancel existing bookings, enhancing the system's flexibility.

### PR DESCRIPTION
**Pull request by Meetpidev**
- If we select (6) then we can modify the all the previous details including name, pickUp and destination poiint, category and number of travelers, 

- Based on the Pickup point , Destination Point and Number of Travelers, it also updateing the Total pricing that user have to pay..

- when we select (7) we can Canceled our Booking.. 

Screenshot 2024-10-22 201955
Screenshot 2024-10-22 202053
Screenshot 2024-10-22 202110

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR

**Comment by soni-shashan** [comment]
### Provide a menu of cities for the user to choose from The user can select a number between 1 and 10 to handle input errors. In the `Enter New Destination` section for ticket modification, prompt the user to select a new city from the menu, or choose 0 if they do not wish to change the destination.

**Comment by Meetpidev** [comment]
@soni-shashan Done.. Please Review PR

**Comment by Meetpidev** [comment]
@soni-shashan Changes are implemented.. requested to review PR

**Pull request merged**
