### PR TITLE
Dynamic Seat Booking..

### PR DESCRIPTION
**Pull request by Meetpidev**
We can book tickets dynamically...

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR...

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR...

**Comment by soni-shashan** [comment]
image

**Comment by soni-shashan** [comment]
### Note: Before starting new work, make sure to pull and merge the latest changes from the repository.

**Comment by Meetpidev** [comment]
@soni-shashan im working on this.. to solve this issue

**Comment by Meetpidev** [comment]
@soni-shashan Requested to revew PR.. i updated Code..

**Pull request merged**
