### PR TITLE
Report Analysis

### LINKED ISSUE #29: Reporting and Analytics
###  Implement features for generating reports and analytics on booking trends, popular destinations, or revenue statistics.

### PR DESCRIPTION
**Pull request by Meetpidev**
Report Analysis includes Popular destinations, Revenuew Statistics... 

Screenshot 2024-10-22 215240

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Requested To Review PR..

**Comment by Meetpidev** [comment]
@soni-shashan Requested to Review PR

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR..

**Comment by soni-shashan** [comment]
### you previous pr having issue , exit without save => delete conformed last booking

**Comment by soni-shashan** [comment]
### Please resolve this issue in the PR, and I will merge it afterward.

**Comment by Meetpidev** [comment]
@soni-shashan Please describe me what is the issue in that ?

**Comment by soni-shashan** [comment]
### first time run
image
### second time run
image

you can see book ticket is removed in second time without any cancel

**Comment by Meetpidev** [comment]
@soni-shashan In the result the details are saved and booked tickets information.. when we confirm the tickets its booked and its save but when we choose exitwithout saving that means tickets are not confirmed by user so we dont print it and simply remove from booked and saved list..

**Comment by soni-shashan** [comment]
### but once it is confirmed then we save and exit, after we run the program then click on exit without save the last ticket is automatically removed

**Comment by Meetpidev** [comment]
@soni-shashan means we want that ifwe select (4) then tickets are booked but dont save .. right ?

**Comment by soni-shashan** [comment]
### no if we select 4 then tickets are already booked do not remove it, if the currently running program make changes is removed but already previously saved ticket is not remove
image
I think line 628 having issue

**Comment by Meetpidev** [comment]
@soni-shashan But the information is not saved by user then how can we say that tickets are booked ? thats why i removed from the boked tickets list..

**Comment by Meetpidev** [comment]
> ### no if we select 4 then tickets are already booked do not remove it, if the currently running program make changes is removed but already previously saved ticket is not remove
> image I think line 628 having issue

The logic is removed only current user booking information..  not whole booked information.. that booked by other people

**Comment by soni-shashan** [comment]
### information is already saved , Expand your scope brother if we execute first time program then select 3 which is save and exit after run second time without any changes select 4 it will delete last ticket which is already conform by user in first time program run 

### exit without save meaning, currently running programs having some changes which is going to remove not previous one

**Comment by soni-shashan** [comment]
### you can create new pr for this I will merge this pr

**Comment by Meetpidev** [comment]
@soni-shashan Let me clarify the functionality of "Exit without saving'..   if we select "save and exit" then its booked and print in display booking.... and when we select "exit without saving" its pointing to previous tickets that is already confirmed by user.. then currently running programs having some changes which is going to remove....

**Comment by soni-shashan** [comment]
> @soni-shashan Let me clarify the functionality of "Exit without saving'.. if we select "save and exit" then its booked and print in display booking.... and when we select "exit without saving" its pointing to previous tickets that is already confirmed by user.. then currently running programs having some changes which is going to remove....

### right but do not remove previous one executed program conform ticket, currently this variant having this issue

**Pull request merged**
